### ISSUE TITLE
Setup Help

### ISSUE THREAD

**Issue by mlcrow** [sgruby/EyeTVExporter#1]
Reading the description, this sounds exactly like what I'm looking for. Can you help guide me through a setup process? Thanks

**Comment by sgruby** [comment]
I used an AppleScript like the following that ran once a day:

	tell application "Finder"
		with timeout of 86400 seconds
			set yesterdayDate to (current date) - 1 * days
			set eyeTVFolder to "Macintosh HD:Users:mediacenter:Documents:EyeTV Archive"
			set theFiles to (files of folder eyeTVFolder where name extension is "eyetv")
			repeat with theFile in theFiles
				set modDate to modification date of theFile
				if (modDate > yesterdayDate) then
					set posixFileLocation to quoted form of POSIX path of (theFile as alias)
					with timeout of 86400 seconds
						do shell script "/Users/mediacenter/Desktop/ConversionScripts/ProcessVideos -f /usr/local/bin/ffmpeg -p /Users/mediacenter/Plex -e " & posixFileLocation
					end timeout
				end if
			end repeat
		end timeout
	end tell


I no longer use this as I switched to MythTV for my recordings.

Good luck!
